spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/alwaysHurt/spring-cloud-config.git
          search-paths: respo
          username: alwaysHurt
          password: woshi250oooo

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/